version: "3.9"
services:
  postgres:
    container_name: pulsewatch-postgres
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pulsewatch
      - POSTGRES_PASSWORD=pulsewatchpass
      - POSTGRES_DB=pulsewatch
    volumes:
      - pulsewatch-db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - pulsewatch-net

volumes:
  pulsewatch-db-data:

networks:
  pulsewatch-net:
