version: "3.9"
services:
  postgres:
    container_name: pulsewatch-postgres
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pulsewatch
      - POSTGRES_PASSWORD=pulsewatchpass
      - POSTGRES_DB=pulsewatch
    volumes:
      - pulsewatch-db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - pulsewatch-net

  api:
    build:
      context: .
      dockerfile: server/Dockerfile.api
    image: pulsewatch-api:latest
    env_file:
      - server/.env
    environment:
      - DATABASE_URL=postgresql://pulsewatch:pulsewatchpass@postgres:5432/pulsewatch
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - pulsewatch-net

  worker:
    build:
      context: .
      dockerfile: server/Dockerfile.worker
    image: pulsewatch-worker:latest
    env_file:
      - server/.env       # same env (e.g. DATABASE_URL) so Prisma can connect
    environment:
      - DATABASE_URL=postgresql://pulsewatch:pulsewatchpass@postgres:5432/pulsewatch
      - CORS_ORIGIN=http://client:3000
    depends_on:
      - postgres
    networks:
      - pulsewatch-net

  client:
    build:
      context: .            # monorepo root
      dockerfile: client/Dockerfile.client
      args:
        VITE_API_URL: "http://pulsewatch.local:4000"
    image: pulsewatch-client:latest
    ports:
      - "80:80"          # host:container
    depends_on:
      - api
    networks:
      - pulsewatch-net

volumes:
  pulsewatch-db-data:

networks:
  pulsewatch-net:
