version: "3.9"
services:
  postgres:
    container_name: pulsewatch-postgres
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pulsewatch
      - POSTGRES_PASSWORD=pulsewatchpass
      - POSTGRES_DB=pulsewatch
    volumes:
      - pulsewatch-db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - pulsewatch-net

  api:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: pulsewatch-api:latest
    env_file:
      - server/.env
    ports:
      - "4000:4000"
    depends_on:
      - postgres

volumes:
  pulsewatch-db-data:

networks:
  pulsewatch-net:
